version: "3.7"

services:
  db:
    image: postgres
    container_name: db_app
    command: -p 5433
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: "metro_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  parser_news:
    build: .
    env_file:
      - .env
    command: ["/app/docker/parser.sh"]
    depends_on:
      - db

  app:
    build: .
    env_file:
      - .env
    command: ["/app/docker/api.sh"]
    ports:
      - 8000:8000
