"""Create db

Revision ID: 8cf4ea59bd96
Revises: 
Create Date: 2023-04-14 11:46:01.153069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf4ea59bd96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=2048), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('url_picture', sa.String(length=1024), nullable=False),
    sa.Column('datetime_parse', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('title'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
